### ISSUE TITLE
Vector tiles generated via ArcGIS Pro (v1.2) are not rendered correctly.

### ISSUE THREAD

**Issue by shadc** [Esri/esri-leaflet-vector#24]
There is a problem with mapbox-gl rendering vector tiles incorrectly when generated from ArcGIS Pro (v1.2) using the "Indexed" tiling format.  When using the "Flat" tiling format they render as expected.

![v](https://cloud.githubusercontent.com/assets/1339350/21914822/9ad1b65e-d8ea-11e6-83f5-42eac2aa8a2a.png)

**Comment by jgravois** [comment]
thanks for this report.  i was under the impression that the commits within Esri/mapbox-gl-js#indexed-vector-tiles were sufficient to download the appropriate tilemap and omit making requests for non existent tiles.

is your screenshot actually a tileset published using Pro? it looks an awful lot like [...180159](http://www.arcgis.com/home/item.html?id=bd505ce3efff479bb4e87b182f180159) which is a custom style for our hosted global tiles.

**Comment by shadc** [comment]
Yes, it is a Esri hosted tile in the screenshot.  It appears I'm having problems with the rendering of tiles for both my custom vector tiles produced with ArcGIS Pro (as described above) as well as Esri's hosted tiles.  I don't seem to have a problem with my custom vector tiles when using the "Flat" tiling format though.  This might be due to issue #22.  I suspect that something is not right with my mapbox-gl dependency install and is causing the rendering issue.

**Comment by jgravois** [comment]
> I suspect that something is not right with my mapbox-gl dependency install and is causing the rendering issue.

luckily, i've been seeing the same exact thing on my side.  i'll keep digging and see what i can figure out.

**Comment by AlanPew** [comment]
If I'm following this ticket correctly, the reason there is inconsistency is because indexed tiles are staggered in their availability based upon the density of data at that particluar zoom level.  Flat tiles create tiles for every tile slot regardless of density of vector data at that spot.
 
"A more optimized approach that minimizes the size of the tiles is to create and persist index polygons. In this case, the tiles are created following logic to recognize when the feature density is low enough to overzoom content to larger-scale tiles. If a tile with minimal feature detail can also be reused and redrawn at larger scales, saving processing and storage, then the smaller tiles (for larger scales) do not need to be created, stored, requested, or drawn."
http://pro.arcgis.com/en/pro-app/help/mapping/map-authoring/author-a-map-for-vector-tile-creation.htm

Unless I set the maxzoom of the vector tile source in a Mapbox GL style to 14, then I see a lot of missing tiles and a blank rendering of the map because when tiles are not rendered because of low density of data.  ESRI has intended for overzoom in these situations.  Would be awesome if there was a way to set the style to use tile if it was available, or overzoom if not in Mapbox GL, but sounds like something that would need to be hacked on the backend with how tiles are grabbed etc.

**Comment by AlanPew** [comment]
Was able to get around the gaps in indexed vector tiles by duplicating all the layers I was using, and creating sources with everything identical but the maxzoom/minzoom.  When there are tile gaps, then the tiles are rendered with overzoom tiles, otherwise the appropriate tiles render as needed.

ESRI OSM with duplicated layers to avoid issues with indexed vector tiles and mimic full tiles: http://htmlpreview.github.io/?https://gist.githubusercontent.com/AlanPew/b8c1f4b3dcab0b410061d316dc292d69/raw/73deaa43a0f0f41e35af7b0b02209eae414065e8/index.html

ESRI OSM with indexed tiles and gaps in rendered data at higher zoom levels:
http://htmlpreview.github.io/?https://gist.githubusercontent.com/AlanPew/b8c1f4b3dcab0b410061d316dc292d69/raw/73deaa43a0f0f41e35af7b0b02209eae414065e8/index.html
