### ISSUE TITLE
Support for V2 base maps

### ISSUE THREAD

**Issue by tswalters** [Esri/esri-leaflet-vector#47]
Are there any plans to update this plugin to support the Esri V2 basemaps?  We were able to get this plugin to render some of the maps but the ones with images/overlays won't render properly currently.

**Comment by jgravois** [comment]
unfortunately not.

I don't know what would be required and can't spare the time to find out.

**Comment by jgravois** [comment]
this turned out to be a lot easier than i anticipated.

based on the work in #48, i've released [`v2.0.0`](https://github.com/Esri/esri-leaflet-vector/releases/v2.0.0) which supports a variety of v2 basemaps.

### one caveat
in v2 they separated the labels and base for Gray/DarkGray and HumanGeography in two different styles.

since i dont know how to mashup more than one style in mapbox-gl-js (see #38), those basemaps are pretty sparse.
