### ISSUE TITLE
Add support for private layers or layers shared across the organization

### ISSUE THREAD

**Issue by rew-ron** [Esri/esri-leaflet-vector#54]
At the moment there's no way to set the token.

The following doesn't work as expected.
```javascript
  L.esri.Vector.layer('1d', {token: 's0m3+0k3n'})
```

**Comment by jwasilgeo** [comment]
@rew-ron we apologize that this issue from 2019 wasn't addressed earlier! 😮 

Since then we have made a few major updates to this library. If you are still looking for ways to use vector tile basemaps / layers with Leaflet + esri-leaflet, please note that we just refreshed the docs pages and changelogs to reflect what's new at esri-leaflet and esri-leaflet-vector v3.

More specifically, the API has changed and it supports apiKeys / tokens for vector tile services that are not shared publicly.

- https://github.com/Esri/esri-leaflet-vector#example
- https://github.com/Esri/esri-leaflet-vector#api-reference

I'll close this with the hope that this will work now with the latest library versions, but do let us know if there are still problems for you.

---

Additional reference:

Live examples and API docs:

- https://esri.github.io/esri-leaflet

Related repo changelogs:

- https://github.com/Esri/esri-leaflet/blob/master/CHANGELOG.md
- https://github.com/Esri/esri-leaflet-geocoder/blob/master/CHANGELOG.md
- https://github.com/Esri/esri-leaflet-vector/blob/master/CHANGELOG.md

And check out the ArcGIS for Developers pages focusing on esri-leaflet:

- https://developers.arcgis.com/esri-leaflet/
