### ISSUE TITLE
Npm dependencies using git instead of npm published module

### ISSUE THREAD

**Issue by kragoth** [Esri/esri-leaflet-vector#58]
The mapbox-gl dependency in packages.json is defined as:
`"mapbox-gl": "git+https://github.com/Esri/mapbox-gl-js.git#indexed-vector-sources",`

This causes issues in enterprise environments which use npm proxies to install dependencies.
As mapbox-gl has a properly published npm module can we please change the dependency to:
`"mapbox-gl": "^1.6.1",`

**Comment by jgravois** [comment]
given the information in #57, that's a good idea, although I'd recommend using `"mapbox-gl": "^1.0.0"`.

**Comment by jwasilgeo** [comment]
@kragoth can you re-evaluate this issue with the new v3 version of this library. We now define it like this:

https://github.com/Esri/esri-leaflet-vector/blob/v3.0.0/package.json#L13

**Comment by jwasilgeo** [comment]
@kragoth we just refreshed the docs pages and changelogs to reflect what's new at esri-leaflet and esri-leaflet-vector v3. I'll close for now due to inactivity but feel free to reopen if still encountering issues, particularly at the newer library versions. Thanks.

Live examples and API docs:

- https://esri.github.io/esri-leaflet

Related repo changelogs:

- https://github.com/Esri/esri-leaflet/blob/master/CHANGELOG.md
- https://github.com/Esri/esri-leaflet-geocoder/blob/master/CHANGELOG.md
- https://github.com/Esri/esri-leaflet-vector/blob/master/CHANGELOG.md

And check out the ArcGIS for Developers pages focusing on esri-leaflet:

- https://developers.arcgis.com/esri-leaflet/

**Comment by jwasilgeo** [comment]
Great—glad to hear that!
