### ISSUE TITLE
Esri-leaflet connected to ArcGIS Enterprise - Vector Tile service not working

### ISSUE THREAD

**Issue by Getiem** [Esri/esri-leaflet-vector#80]
I created a vector tile service on my ArcGIS Enterprise 10.7.1 and added it to Esri Leaflet. However, it is not showing any data. It is showing an error on every request with empty JSON.

Uploading the same vectortile package published to ArcGIS Online as service. This service works in Esri-Leaflet.

Can you find what the problem is, and fix it?

Thanks!

**Comment by rvschouwen** [comment]
It seems there is a difference in default behavior between ArcGIS Online and ArcGIS Enterprise. The used code results in two requests to the VectorTIleServer, the first one being:
`https://tiles.arcgis.com/tiles/<ID>/arcgis/rest/services/Basemap_WGS84/VectorTileServer?token=<TOKEN>&f=json`
for ArcGIS Online, and:
`https://<arcgisenterpriseserver>/arcgishosted/rest/services/Hosted/Outdoor_basemap/VectorTileServer?token=<TOKEN>&f=json`
for ArcGIS Enterprise.

The second request is this:
`https://tiles.arcgis.com/tiles/<ID>/arcgis/rest/services/Basemap_WGS84/VectorTileServer?token=<TOKEN>`
for ArcGIS Online, and:
`https://<arcgisenterpriseserver>/arcgishosted/rest/services/Hosted/Outdoor_basemap/VectorTileServer?token=<TOKEN>`
for ArcGIS Enterprise.

So the same request, but without the f=json part. On ArcGIS Online, this returns a JSON formatted page, on ArcGIS Enterprise, this results in an HTML formatted page, generating an error:
`Error: Unexpected token < in JSON at position 0
    at mapbox-gl.js:29`

It seems like this can be fixed by appending the output format selector to the request to the service. To test this, I have proxied the request and added the "f=json" to the query string in the proxy, after which it works as expected.

**Comment by jwasilgeo** [comment]
We hope to have this issue fixed when we release a new version of this library, [following the current v3.0.1](https://github.com/esri/esri-leaflet-vector/compare/v3.0.1...HEAD).

**Comment by jwasilgeo** [comment]
This is available now in the recent [v3.1.0 release](https://github.com/Esri/esri-leaflet-vector/releases/tag/v3.1.0). 🎉
